### PR TITLE
First write up of my slides

### PR DESCRIPTION
**Pull request by Nikoleta-v3**
These slides are for the SSI selection day.

In the who I am the pictures need better positioning (need to ask Vince for a tip on how to do this).
Not sure if the length is appropriate, will be discussed.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Try and tweak these based on our very short chat earlier today. We'll talk about it properly this week.

**Comment by Nikoleta-v3** [comment]
On your comments: 

- I am planning on making an important point on workshops in the UK. To encourage people from all  "levels" and I am using the Human class to point out that software can be fun. 

- About Namibia: International student lack information of the possibilities they have in the computing world and the opportunities in the UK.

**Comment by drvinceknight** [comment]
> I am planning on making an important point on workshops in the UK. To encourage people from all "levels" and I am using the Human class to point out that software can be fun.

All "levels" makes it sound like you want to teach programming. Remember that this is about sustainable software practice. Perhaps have another read through the various things the SSI does and what their goals are.

Also: the color scheme is poor, the light grey won't be clear on the background.

> 
> About Namibia: International student lack information of the possibilities they have in the computing world and the opportunities in the UK.

Do they [Namibians in particular] lack that information? How do you know? What possibilities do they have? Not convinced by this.

Your slides are very dispersed and it does not aim to get your main message across. **What is your main message?**

**Comment by Nikoleta-v3** [comment]
My goal would be to apply and encourage SSI in the field of Game Theory. Which field has suffered from the lack of sustainable and reproducible software (will explain why). Being part of the SSI would allow me:

- To build up my own knowledge on software development. 
- This will allow me to build up Axelrod and various other tools I will be using for my research
- Spread the word in the Game Theory community. 
- Inspire new generations in the field

**Comment by drvinceknight** [comment]
> My goal would be to apply and encourage SSI in the field of Game Theory. 

Not encourage the SSI. Encourage Sustainable Software practice.

So immediately the question I would have is: what exists in terms of software in the field of Game Theory? A part from IPD work, is the situation bad? better? Worse?

> Which field has suffered from the lack of sustainable and reproducible software (will explain why). 

> Being part of the SSI would allow me:
> 
> To build up my own knowledge on software development.

What benefit does that bring to the SSI?

> This will allow me to build up Axelrod and various other tools I will be using for my research

What benefit does that bring to the SSI?

> Spread the word in the Game Theory community.

What impact does spreading the word have?

> Inspire new generations in the field

What does inspiring new generations in the field have to do with the SSI and it's goals?

What are the goals of the SSI. How do your goals align with them.

**Comment by Nikoleta-v3** [comment]
#5 Closes this.

**Pull request closed without merging**
